#define main old_main
#include "tao_d256_api.cpp"
#undef main
#include <array>
int main() {
    const char* files[]={"experiments/d256_nibble64_baseline/train_tokens.bin","experiments/d256_nibble64_baseline/eval_tokens.bin","experiments/d256_nibble64_baseline/multislice/slice_0.bin"};
    for(auto path:files){std::ifstream in(path,std::ios::binary);uint32_t n=0;in.read((char*)&n,4);std::array<uint64_t,1024> counts{};std::vector<int> buf(262144);uint64_t read=0,transitions=0;int prev=-1;while(read<n){size_t take=std::min(uint64_t(buf.size()),uint64_t(n)-read);if(!in.read((char*)buf.data(),take*4))return 2;for(size_t i=0;i<take;++i){int id=buf[i];if(id<0||id>=1024)return 3;counts[id]++;transitions+=prev==1&&id==1;prev=id;}read+=take;}printf("CORPUS %s tokens=%u PAD=%llu UNK=%llu EOS=%llu UNK_percent=%.6f adjacent_UNK=%llu\n",path,n,(unsigned long long)counts[0],(unsigned long long)counts[1],(unsigned long long)counts[2],100.0*counts[1]/n,(unsigned long long)transitions);}
    std::ifstream f("tinystories_train.txt",std::ios::binary);std::string text(5000000,0);f.read(text.data(),text.size());text.resize(size_t(f.gcount()));Vocab vocab;vocab.build(text,1024);auto ids=vocab.encode(text);uint64_t unknown=std::count(ids.begin(),ids.end(),1);printf("VOCAB first5Mbytes tokens=%zu UNK=%llu rate=%.6f\n",ids.size(),(unsigned long long)unknown,100.0*unknown/ids.size());
    std::string normalized=text;for(char& c:normalized)c=char(std::tolower((unsigned char)c));Vocab candidate;candidate.build(normalized,1024);auto proposed=candidate.encode(text);auto missing_count=std::count(proposed.begin(),proposed.end(),1);printf("CANDIDATE lower-build/lower-encode same5Mbytes UNK=%llu rate=%.6f NOTE new IDs incompatible with old checkpoints\n",(unsigned long long)missing_count,100.0*missing_count/proposed.size());
    std::map<std::string,uint64_t> missing;std::string word;auto flush=[&](){if(!word.empty()){std::string lower=word;for(char& c:lower)c=char(std::tolower((unsigned char)c));if(vocab.encode_word(lower)==1)missing[lower]++;word.clear();}};for(unsigned char c:text){if(std::isspace(c)||std::ispunct(c))flush();else word+=char(c);}flush();std::vector<std::pair<std::string,uint64_t>> ranked(missing.begin(),missing.end());std::sort(ranked.begin(),ranked.end(),[](auto&a,auto&b){return a.second>b.second;});for(size_t i=0;i<std::min(size_t(25),ranked.size());++i)printf("MISSING %s %llu\n",ranked[i].first.c_str(),(unsigned long long)ranked[i].second);return 0;
}
