#define CONTROLLED_READOUT_LIBRARY
#include "train_controlled_readout.cu"
#undef main
#include <numeric>

struct Projection {std::vector<float> base, terms;};
Projection project(const Data& data,const std::vector<float>& w,ServerCore& core){
    Projection out;out.base.resize(data.records.size()*Classes);out.terms.resize(data.records.size()*15*Classes);
    for(size_t n=0;n<data.records.size();++n){
        for(int c=0;c<Classes;++c)for(int f=0;f<Features;++f)out.base[n*Classes+c]+=w[c*Features+f]*data.x[n*Features+f];
        SelfDecodingNode<16,256> node;for(int id:data.records[n].input)node.push(id,[&](int id){return core.q1.code(id);});
        for(int k=1;k<=15;++k){node.pop([&](int id){return core.q1.code(id);});for(int c=0;c<Classes;++c)for(int d=0;d<256;++d)out.terms[(n*15+k-1)*Classes+c]+=w[c*Features+d]*core.reader_sel[k*256+d]*node.trit[d];}
    }return out;
}
std::array<float,Classes> logits(const Projection& p,size_t n,const uint8_t* codes){std::array<float,Classes> z;std::copy_n(&p.base[n*Classes],Classes,z.begin());for(int k=0;k<15;++k)if(codes[k])for(int c=0;c<Classes;++c)z[c]+=(tds::scale(codes[k])-1)*p.terms[(n*15+k)*Classes+c];return z;}
double objective(const Data& data,const Projection& p,int query,const uint8_t* codes){double sum=0;int count=0;for(size_t n=0;n<data.records.size();++n)if(data.records[n].input[63]==query){auto z=logits(p,n,codes);double mx=*std::max_element(z.begin(),z.end()),s=0;for(float v:z)s+=std::exp(double(v)-mx);sum+=mx+std::log(s)-z[data.y[n]];++count;}return sum/count;}
void report(const char* tag,const Data& data,const Projection& p,const std::vector<uint8_t>& gates){for(int query=900;query<907;++query){int num=0,correct=0,binary=0;for(size_t n=0;n<data.records.size();++n)if(data.records[n].input[63]==query){auto z=logits(p,n,&gates[query*15]);correct+=std::max_element(z.begin(),z.end())-z.begin()==data.y[n];binary+=z[data.y[n]]>z[data.records[n].alternate-128];++num;}printf("RESULT %s query=%d N=%d CE=%.9f top1=%.6f binary=%.6f\n",tag,query,num,objective(data,p,query,&gates[query*15]),double(correct)/num,double(binary)/num);}}
int main(int argc,char**argv){try{if(argc!=2)return 1;setvbuf(stdout,nullptr,_IONBF,0);std::string root=argv[1];for(int seed:{42,123,2026})for(int policy:{0,1})if(std::filesystem::exists(root+"/search_seed"+std::to_string(seed)+"_policy"+std::to_string(policy)+".bin"))throw std::runtime_error("refuse existing search before execution");ServerCore core;if(!core.load("tao_fixed_step50002.bin","tao_context_supported.tcg","tao_coef_rts1_128.reader","tinystories_train.txt","experiments/d256_nibble64_baseline/train_tokens.bin"))return 2;auto train=load(root+"/train.bin",core),test=load(root+"/test_context.bin",core);for(int seed:{42,123,2026}){std::vector<float>w(Classes*Features);std::ifstream in(root+"/readout_seed"+std::to_string(seed)+".bin",std::ios::binary);in.read((char*)w.data(),w.size()*4);if(!in)throw std::runtime_error("readout missing");auto tp=project(train,w,core),ep=project(test,w,core);printf("READOUT_SEED %d\n",seed);std::vector<uint8_t> identity(1024*15,0);report("identity_test",test,ep,identity);for(int random_order:{0,1}){auto gates=identity;int evaluated=0,slots=0;std::mt19937 rng(7331);for(int query=900;query<907;++query){std::vector<int> order(15);std::iota(order.begin(),order.end(),0);if(random_order)std::shuffle(order.begin(),order.end(),rng);printf("ORDER policy=%d query=%d",random_order,query);for(int k:order)printf(" %d",k+1);printf("\n");double current=objective(train,tp,query,&gates[query*15]);for(int k:order){int idx=query*15+k;uint8_t selected=gates[idx];double best=current;for(uint8_t code=1;code<=8;++code){++slots;gates[idx]=code;int active=0,budget=0;for(int j=0;j<15;++j){active+=(gates[query*15+j]!=0||core.gates[query*15+j]!=0);budget+=tds::magnitude(gates[query*15+j]);}if(active>2||budget>8)continue;++evaluated;double trial=objective(train,tp,query,&gates[query*15]);if(trial<best){best=trial;selected=code;}}gates[idx]=selected;current=best;}printf("SELECT query=%d train_CE=%.9f",query,current);for(int k=0;k<15;++k)if(gates[query*15+k])printf(" k%d:code%d",k+1,int(gates[query*15+k]));printf("\n");}tds::validate_codes(gates);tds::validate_union(gates,core.gates);printf("BUDGET policy=%d candidate_slots=%d feasible_evaluations=%d\n",random_order,slots,evaluated);report(random_order?"random_test":"ascending_test",test,ep,gates);std::string path=root+"/search_seed"+std::to_string(seed)+"_policy"+std::to_string(random_order)+".bin";if(std::filesystem::exists(path))throw std::runtime_error("refuse search overwrite");std::ofstream out(path,std::ios::binary);out.write((char*)gates.data(),gates.size());if(!out)throw std::runtime_error("search save");}}return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 10;}}
