#define main serving_main
#include "tao_d256_api.cpp"
#undef main
#include <cuda_runtime.h>
#include <filesystem>
#ifndef CONTROLLED_READOUT_LIBRARY
int controlled_readout_main(int argc,char** argv);
int main(int argc,char** argv){return controlled_readout_main(argc,argv);}
#endif

constexpr int Features=321, Classes=32;
struct RetrievalRecord {std::array<int32_t,64> input;int32_t target,alternate,distance,pair;};
void check(cudaError_t e){if(e!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(e));}
template<class T> T* device(const std::vector<T>& data){T* p;check(cudaMalloc(&p,data.size()*sizeof(T)));check(cudaMemcpy(p,data.data(),data.size()*sizeof(T),cudaMemcpyHostToDevice));return p;}
__global__ void predict(const float* x,const float* w,float* z,int rows){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=rows*Classes)return;int n=i/Classes,c=i%Classes;float sum=0;for(int f=0;f<Features;++f)sum+=x[n*Features+f]*w[c*Features+f];z[i]=sum;}
__global__ void residual(float* z,const int* y,int rows){int n=blockIdx.x*blockDim.x+threadIdx.x;if(n>=rows)return;float mx=z[n*Classes],sum=0;for(int c=1;c<Classes;++c)mx=fmaxf(mx,z[n*Classes+c]);for(int c=0;c<Classes;++c){z[n*Classes+c]=expf(z[n*Classes+c]-mx);sum+=z[n*Classes+c];}for(int c=0;c<Classes;++c)z[n*Classes+c]=z[n*Classes+c]/sum-float(c==y[n]);}
__global__ void update(float* w,const float* x,const float* dz,int rows){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i>=Classes*Features)return;int c=i/Features,f=i%Features;float grad=0;for(int n=0;n<rows;++n)grad+=x[n*Features+f]*dz[n*Classes+c];w[i]-=.05f*(grad/rows+.001f*w[i]);}
struct Data {std::vector<RetrievalRecord> records;std::vector<float> x;std::vector<int> y;};
Data load(const std::string& path,ServerCore& core){std::ifstream in(path,std::ios::binary);uint32_t h[5];in.read((char*)h,20);if(!in||h[0]!=0x31525443||h[1]!=1||h[3]!=64||h[4]!=272||h[2]>100000)throw std::runtime_error("dataset header");Data data;data.records.resize(h[2]);in.read((char*)data.records.data(),h[2]*272);if(!in)throw std::runtime_error("dataset read");for(auto& r:data.records){SelfDecodingNode<16,256> node;for(int id:r.input){if(id<0||id>=1024)throw std::runtime_error("token ID");node.push(id,[&](int id){return core.q1.code(id);});}auto view=node;float mixed[256]={};for(int k=0;;++k){for(int d=0;d<256;++d)mixed[d]+=float(core.reader_sel[k*256+d])*view.trit[d];if(!view.count)break;view.pop([&](int id){return core.q1.code(id);});}for(float value:mixed)data.x.push_back(value);for(int i=0;i<64;++i)data.x.push_back(float((node.hash>>(4*(i&7)))&15)/15-.5f);data.x.push_back(1);if(r.target<128||r.target>=160)throw std::runtime_error("answer ID");data.y.push_back(r.target-128);}return data;}
void evaluate(const char* label,const Data& data,const std::vector<float>& w){double loss[7]={};int correct[7]={},binary[7]={},counts[7]={};int distances[]={2,4,8,15,16,32,64};for(size_t n=0;n<data.y.size();++n){float z[Classes]={};for(int c=0;c<Classes;++c)for(int f=0;f<Features;++f)z[c]+=w[c*Features+f]*data.x[n*Features+f];int d=int(std::find(distances,distances+7,data.records[n].distance)-distances);double mx=*std::max_element(z,z+Classes),sum=0;for(float v:z)sum+=std::exp(double(v)-mx);loss[d]+=mx+std::log(sum)-z[data.y[n]];correct[d]+=std::max_element(z,z+Classes)-z==data.y[n];binary[d]+=z[data.y[n]]>z[data.records[n].alternate-128];counts[d]++;}for(int d=0;d<7;++d)printf("EVAL %s d=%d N=%d CE=%.9f top1=%.6f binary=%.6f\n",label,distances[d],counts[d],loss[d]/counts[d],double(correct[d])/counts[d],double(binary[d])/counts[d]);}
int controlled_readout_main(int argc,char** argv){try{if(argc!=2)return 1;setvbuf(stdout,nullptr,_IONBF,0);std::string root=argv[1];for(int seed:{42,123,2026})if(std::filesystem::exists(root+"/readout_seed"+std::to_string(seed)+".bin"))throw std::runtime_error("refuse existing readout before training");ServerCore core;if(!core.load("tao_fixed_step50002.bin","tao_context_supported.tcg","tao_coef_rts1_128.reader","tinystories_train.txt","experiments/d256_nibble64_baseline/train_tokens.bin"))return 2;auto train=load(root+"/train.bin",core),test=load(root+"/test_context.bin",core),unseen=load(root+"/test_unseen_answers.bin",core);printf("Auxiliary32-class linear readout on frozen raw reader/hash features; NOT production head; unseen16 classes have no positive train supervision; primary test disjoint contexts\n");auto x=device(train.x);auto y=device(train.y);float* z;check(cudaMalloc(&z,train.y.size()*Classes*sizeof(float)));for(int seed:{42,123,2026}){std::mt19937 rng(seed);std::normal_distribution<float> normal(0,.001f);std::vector<float>w(Classes*Features);for(auto& v:w)v=normal(rng);auto dw=device(w);predict<<<(int(train.y.size())*Classes+255)/256,256>>>(x,dw,z,int(train.y.size()));std::vector<float> gpu(train.y.size()*Classes);check(cudaMemcpy(gpu.data(),z,gpu.size()*4,cudaMemcpyDeviceToHost));double err=0;for(int n=0;n<16;++n)for(int c=0;c<Classes;++c){float cpu=0;for(int f=0;f<Features;++f)cpu+=w[c*Features+f]*train.x[n*Features+f];err=std::max(err,double(std::abs(cpu-gpu[n*Classes+c])));}if(err>1e-5)throw std::runtime_error("CPU GPU logits");printf("SEED %d initial CPU/GPU max_abs=%.9g\n",seed,err);evaluate("initial_test",test,w);for(int step=0;step<100;++step){predict<<<(int(train.y.size())*Classes+255)/256,256>>>(x,dw,z,int(train.y.size()));residual<<<(int(train.y.size())+255)/256,256>>>(z,y,int(train.y.size()));update<<<(Classes*Features+255)/256,256>>>(dw,x,z,int(train.y.size()));check(cudaGetLastError());}check(cudaMemcpy(w.data(),dw,w.size()*4,cudaMemcpyDeviceToHost));evaluate("trained_train",train,w);evaluate("trained_test",test,w);evaluate("unseen_classes_exploratory",unseen,w);std::string output=root+"/readout_seed"+std::to_string(seed)+".bin";if(std::filesystem::exists(output))throw std::runtime_error("refuse readout overwrite");std::ofstream out(output,std::ios::binary);out.write((char*)w.data(),w.size()*4);out.close();std::string featurefile=root+"/train_features.f32";if(seed==42){std::ofstream features(featurefile,std::ios::binary);features.write((char*)train.x.data(),train.x.size()*4);}check(cudaFree(dw));}check(cudaFree(x));check(cudaFree(y));check(cudaFree(z));return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 10;}}
