#define NOMINMAX
#define TAO_INPUT_SCALE
#define TAO_DEVICE_ZERO_GRAD
#include "slot_checkpoint_file.cuh"
#include "dual_state_initialization.hpp"
#include "bpe_pilot_reader.hpp"
#include "tokenizer_file.hpp"
#include "dual_loss_parallel.cuh"
#include <cstdio>
int main(){try{using namespace tao::dual;using namespace tao::data;std::string th;auto tok=tao::text::load_tokenizer("build/formal_tokenizer.bbp",th);std::ifstream f("build/bpe_pilot_train.bin",std::ios::binary);std::string raw((std::istreambuf_iterator<char>(f)),{});std::istringstream in(raw);auto docs=read_bpe_pilot(in,th);std::vector<std::vector<Token>> selected;std::vector<size_t>sources;for(size_t d=0;d<docs.size()&&selected.size()<4;++d){auto&t=docs[d];if(t.size()>64||t.size()<8||t[1].id!=USER)continue;size_t a=0,roles=0;for(size_t i=1;i<t.size();++i)if(t[i].id==ASSISTANT){a=i;++roles;}if(roles!=1||!a||t[a-1].id!=TURN_END||t.size()-a-2<2||t.size()-a-2>24)continue;selected.push_back(t);sources.push_back(d);}if(selected.size()!=4)throw std::runtime_error("not enough short QA");
SortedGpuTrainer tr(initialize(Config{},713));SequenceSlots slots(tr,4);PilotCursor cursor(docs,4,false);auto id=checkpoint_identity(tr.graph.c,tao::text::sha256(raw),th,200)+"arch2-warmstart63-reset-adam-state-data-warmup4-cosine196\n";{auto fresh=capture(slots,cursor);auto source=load_slot_file("build/yaoyao_arch2_step_20.scp",id,fresh,cursor);fresh.w=std::move(source.w);restore(fresh,slots,cursor);}auto cpu_model=[&](){CpuModel cpu(tr.graph.c);for(auto&kv:cpu.w)kv.second=tr.graph.w.at(kv.first)->value.host();return cpu;};
auto report=[&](unsigned step){auto cpu=cpu_model();for(size_t k=0;k<4;++k){auto&t=selected[k];size_t a=1;while(t[a].id!=ASSISTANT)++a;std::vector<uint32_t>q,answer;for(size_t i=2;i<a-1;++i)q.push_back(t[i].id);for(size_t i=a+1;i<t.size()-1;++i)answer.push_back(t[i].id);auto state=cpu.initial();Vec logits;for(size_t i=0;i<=a;++i)logits=cpu.step(t[i].id,state);float mx=*std::max_element(logits.begin(),logits.end());double z=0;for(float x:logits)z+=exp(double(x)-mx);printf("PROBE step=%u sample=%zu source_doc=%zu first_target=%u p_first=%.9f p_end=%.9f\n",step,k,sources[k],answer[0],exp(double(logits[answer[0]])-mx)/z,exp(double(logits[259])-mx)/z);auto hex=[](const char*label,const std::string&s){printf("%s ",label);for(unsigned char c:s)printf("%02x",c);printf("\n");};hex("QUESTION_HEX",tok.decode(q));hex("REFERENCE_HEX",tok.decode(answer));std::vector<uint32_t>out;int end=-1;for(int i=0;i<32;++i){for(unsigned j:{256u,257u,258u})logits[j]=-std::numeric_limits<float>::infinity();unsigned v=std::max_element(logits.begin(),logits.end())-logits.begin();if(v==259||v==260){end=v;break;}out.push_back(v);logits=cpu.step(v,state);}hex("OUTPUT_HEX",tok.decode(out));printf("END %d tokens=%zu\n",end,out.size());}fflush(stdout);};
report(0);BlockLoss lossbuf(64);for(unsigned step=1;step<=100;++step){double loss=0;size_t n=0;for(size_t k=0;k<4;++k){slots.begin(k,true);auto&t=selected[k];for(size_t i=1;i<t.size();++i){auto y=tr.graph.step(t[i-1].id);lossbuf.seed(y,t[i].id,t[i].loss);n+=t[i].loss;}loss+=lossbuf.collect();slots.finish(true);}float norm=tr.update(n,.0003f);printf("TRAIN step=%u supervised=%zu NLL=%.9f norm=%.6f\n",step,n,loss/n,norm);fflush(stdout);if(step==25||step==100)report(step);}save_bundle(cpu_model(),"build/capability_probe_final.dsb",th);return 0;}catch(const std::exception&e){printf("FAIL %s\n",e.what());return 1;}}
