#define NOMINMAX
#define TAO_INPUT_SCALE
#define TAO_CPU_AVX2
#include "tokenizer_file.hpp"
#include "advance_row_parallel_byte_cpu_model.hpp"
#include <iostream>
#include <chrono>
// Generation/end/reset/token accounting unchanged; only prompt discarded heads skipped.
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("model required");auto start=std::chrono::steady_clock::now();std::string hash;auto tokenizer=tao::text::load_tokenizer("build/formal_tokenizer.bbp",hash);auto model=tao::dual::AdvanceRowParallelByteCpuModel(tao::dual::read_compact_bundle(argv[1],hash));auto state=model.initial();bool fresh=true;std::cerr<<"READY loads=1 load_seconds="<<std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count()<<std::endl;std::string prompt;size_t request=0;while(std::getline(std::cin,prompt)){if(prompt=="/quit")break;if(prompt=="/reset"){state=model.initial();fresh=true;std::cout<<"RESET"<<std::endl;continue;}if(prompt.size()>8192){std::cout<<"ERROR prompt exceeds8192bytes"<<std::endl;continue;}auto begin=std::chrono::steady_clock::now();tao::dual::Vec logits;if(fresh){model.advance(256,state);fresh=false;}model.advance(257,state);for(auto t:tokenizer.encode(prompt))model.advance(t,state);model.advance(259,state);logits=model.step(258,state);auto first=begin,last=begin;std::vector<uint32_t>ids;int end=-1;for(int i=0;i<64;++i){for(float v:logits)if(!std::isfinite(v))throw std::runtime_error("nonfinite");for(unsigned t:{256u,257u,258u})logits[t]=-std::numeric_limits<float>::infinity();unsigned t=std::max_element(logits.begin(),logits.end())-logits.begin();auto now=std::chrono::steady_clock::now();if(t==259||t==260){model.advance(t,state);end=t;if(t==260){state=model.initial();fresh=true;}break;}if(ids.empty())first=now;last=now;ids.push_back(t);if(i==63)model.advance(t,state);else logits=model.step(t,state);}if(end<0)model.advance(259,state);auto output=tokenizer.decode(ids);std::cout<<"BEGIN_REPLY "<<++request<<"\n"<<(output.empty()?"[empty reply]":output)<<"\nEND_REPLY tokens="<<ids.size()<<" end="<<end<<" truncated="<<(end<0)<<" loads=1";if(!ids.empty())std::cout<<" ttft_compute="<<std::chrono::duration<double>(first-begin).count();if(ids.size()>1)std::cout<<" decode_tps="<<(ids.size()-1)/std::chrono::duration<double>(last-first).count();else std::cout<<" decode_tps=NA";std::cout<<std::endl;}return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<std::endl;return 1;}}
