#include <array>
#include <vector>
#include <random>
#include <cmath>
#include <cstdio>
#include <stdexcept>
#include <algorithm>
using Memory=std::array<double,8>;using Weights=std::array<double,81>;
struct Event{int object,owner;};struct Sequence{int query,target;std::vector<Event>events;};
struct Gate{Weights w;Gate(unsigned seed){std::mt19937 rng(seed);std::normal_distribution<double>d(0,.2);for(auto&x:w)x=d(rng);}double probability(int q,int o)const{double z=w[80];for(int i=0;i<8;++i)z+=w[72+i]*std::tanh(w[i*9+8]+w[i*9+q]+w[i*9+4+o]);return z>=0?1/(1+std::exp(-z)):std::exp(z)/(1+std::exp(z));}void back(int q,int o,double dz,Weights&g)const{g[80]+=dz;for(int i=0;i<8;++i){double h=std::tanh(w[i*9+8]+w[i*9+q]+w[i*9+4+o]);g[72+i]+=dz*h;double da=dz*w[72+i]*(1-h*h);g[i*9+8]+=da;g[i*9+q]+=da;g[i*9+4+o]+=da;}}};
double loss(const Gate&g,const Sequence&s,Weights*gradient=nullptr,int*softanswer=nullptr,int*hardanswer=nullptr){std::vector<Memory>states(s.events.size()+1);states[0].fill(1./8);std::vector<double>p(s.events.size());int hard=-1;for(size_t t=0;t<s.events.size();++t){auto e=s.events[t];p[t]=g.probability(s.query,e.object);if(p[t]>=.5)hard=e.owner;for(int k=0;k<8;++k)states[t+1][k]=(1-p[t])*states[t][k]+p[t]*(k==e.owner);}auto&m=states.back();if(softanswer)*softanswer=int(std::max_element(m.begin(),m.end())-m.begin());if(hardanswer)*hardanswer=hard;if(!(m[s.target]>0))throw std::runtime_error("zero target probability");double ce=-std::log(m[s.target]);if(gradient){Memory dm{};dm[s.target]=-1/m[s.target];for(size_t t=s.events.size();t-->0;){double dp=0;for(int k=0;k<8;++k)dp+=dm[k]*((k==s.events[t].owner)-states[t][k]);g.back(s.query,s.events[t].object,dp*p[t]*(1-p[t]),*gradient);for(auto&v:dm)v*=1-p[t];}}return ce;}
Sequence make(std::mt19937&r,int noise){Sequence s;s.query=r()%4;int owner=r()%8;s.events.push_back({s.query,owner});for(int j=0;j<2;++j){for(int i=0;i<noise;++i)s.events.push_back({(s.query+1+int(r()%3))%4,int(r()%8)});if(j==0&&r()%2){owner=(owner+1+int(r()%7))%8;s.events.push_back({s.query,owner});}}s.target=owner;return s;}
int main(){try{for(unsigned seed:{42u,123u,2026u}){Gate g(seed);std::mt19937 rng(seed+111);auto fixture=make(rng,2);Weights grad{};loss(g,fixture,&grad);double err=0;for(int i=0;i<81;++i){double old=g.w[i],eps=1e-6;g.w[i]=old+eps;double hi=loss(g,fixture);g.w[i]=old-eps;double lo=loss(g,fixture);g.w[i]=old;err=std::max(err,std::abs((hi-lo)/(2*eps)-grad[i]));}if(err>1e-7)throw std::runtime_error("BPTT gradient mismatch");double initial=0;std::vector<Sequence>train;for(int i=0;i<512;++i)train.push_back(make(rng,rng()%3));for(auto&s:train)initial+=loss(g,s);for(int step=0;step<2000;++step){grad.fill(0);for(auto&s:train)loss(g,s,&grad);for(int i=0;i<81;++i)g.w[i]-=.2*(grad[i]/train.size()+.0001*g.w[i]);}double final=0;for(auto&s:train)final+=loss(g,s);printf("seed=%u gradient_error=%.12g trainCE %.9f -> %.9f\n",seed,err,initial/train.size(),final/train.size());for(int noise:{0,2,8,32,128}){std::mt19937 test(9001+noise);int softok=0,hardok=0,always=0,first=0;double ce=0;for(int i=0;i<512;++i){auto s=make(test,noise);int a,b;ce+=loss(g,s,nullptr,&a,&b);softok+=a==s.target;hardok+=b==s.target;always+=s.events.back().owner==s.target;first+=s.events.front().owner==s.target;}printf("noise_each_side=%d n=512 soft=%.6f hard=%.6f CE=%.9f always=%.6f first=%.6f\n",noise,softok/512.,hardok/512.,ce/512,always/512.,first/512.);}}return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
