#include <array>
#include <vector>
#include <random>
#include <cmath>
#include <cstdio>
#include <string>
#include <algorithm>
#include <stdexcept>
using M=std::array<double,8>;
constexpr int H=16,I=57,O=9,BASE=H*I+O*(H+1),N=BASE+16*17+16*17;
using W=std::array<double,N>;

struct Seq{int query,target;
std::vector<int>tokens;
};

Seq make(std::mt19937&r,int noise){Seq s;
s.query=r()%4;
int owner=r()%8;
auto event=[&](int object,int who){s.tokens.insert(s.tokens.end(),{object,4+who,12});
};
event(s.query,owner);
for(int side=0;
side<2;
++side){for(int i=0;
i<noise;
++i)event((s.query+1+r()%3)%4,r()%8);
if(side==0&&r()%2){owner=(owner+1+r()%7)%8;
event(s.query,owner);
}}s.target=owner;
return s;
}
struct Cache{std::array<int,6>ix;
std::array<double,H>h,a;
std::array<double,16>u;
double p;
M v,m;
};

struct Net{W w;
Net(unsigned seed){std::mt19937 r(seed);
std::normal_distribution<double>d(0,.15);
for(auto&v:w)v=d(r);
}
double run(const Seq&s,W*grad=nullptr,int*soft=nullptr,int*hard=nullptr)const{std::vector<Cache>cache(s.tokens.size());
M memory;
memory.fill(.125);
M hardmem=memory;
for(size_t t=0;
t<s.tokens.size();
++t){auto&c=cache[t];
c.ix={s.query,4+s.tokens[t],17+(t? s.tokens[t-1]:12),30+(t>1?s.tokens[t-2]:12),43+(t>2?s.tokens[t-3]:12),56};
c.m=memory;
for(int h=0;
h<H;
++h){double a=0;
for(int i:c.ix)a+=w[h*I+i];
c.h[h]=std::tanh(a);
}c.a=c.h;
for(int j=0;
j<16;
++j){double a=w[BASE+j*17+16];
for(int k=0;
k<16;
++k)a+=w[BASE+j*17+k]*c.a[k];
c.u[j]=std::tanh(a);
}for(int k=0;
k<16;
++k){double a=c.a[k]+w[BASE+272+k*17+16];
for(int j=0;
j<16;
++j)a+=w[BASE+272+k*17+j]*c.u[j];
c.h[k]=std::tanh(a);
}double z[9];
for(int o=0;
o<9;
++o){z[o]=w[H*I+o*(H+1)+H];
for(int h=0;
h<H;
++h)z[o]+=w[H*I+o*(H+1)+h]*c.h[h];
}c.p=std::max(0.,std::min(1.,.5+.25*z[0]));
double mx=*std::max_element(z+1,z+9),sum=0;
for(int k=0;
k<8;
++k){c.v[k]=std::exp(z[k+1]-mx);
sum+=c.v[k];
}for(int k=0;
k<8;
++k){c.v[k]/=sum;
memory[k]=(1-c.p)*memory[k]+c.p*c.v[k];
}if(c.p>=.5)hardmem=c.v;
}if(soft)*soft=int(std::max_element(memory.begin(),memory.end())-memory.begin());
if(hard)*hard=int(std::max_element(hardmem.begin(),hardmem.end())-hardmem.begin());
double ce=-std::log(memory[s.target]);
if(!std::isfinite(ce))throw std::runtime_error("nonfinite loss");
if(grad){M dm{};
dm[s.target]=-1/memory[s.target];
for(size_t t=cache.size();
t-->0;
){auto&c=cache[t];
double dp=0,dot=0;
for(int k=0;
k<8;
++k){dp+=dm[k]*(c.v[k]-c.m[k]);
dot+=dm[k]*c.v[k];
}double dz[9];
dz[0]=dp*((c.p>0&&c.p<1)?.25:0.);
for(int k=0;
k<8;
++k)dz[k+1]=c.p*c.v[k]*(dm[k]-dot);
double dh[H]={};
for(int o=0;
o<9;
++o){(*grad)[H*I+o*(H+1)+H]+=dz[o];
for(int h=0;
h<H;
++h){(*grad)[H*I+o*(H+1)+h]+=dz[o]*c.h[h];
dh[h]+=dz[o]*w[H*I+o*(H+1)+h];
}}double du[16]={},da[16];
for(int k=0;
k<16;
++k){double d=dh[k]*(1-c.h[k]*c.h[k]);
da[k]=d;
(*grad)[BASE+272+k*17+16]+=d;
for(int j=0;
j<16;
++j){(*grad)[BASE+272+k*17+j]+=d*c.u[j];
du[j]+=d*w[BASE+272+k*17+j];
}}for(int j=0;
j<16;
++j){double d=du[j]*(1-c.u[j]*c.u[j]);
(*grad)[BASE+j*17+16]+=d;
for(int k=0;
k<16;
++k){(*grad)[BASE+j*17+k]+=d*c.a[k];
da[k]+=d*w[BASE+j*17+k];
}}for(int h=0;
h<H;
++h)for(int i:c.ix)(*grad)[h*I+i]+=da[h]*(1-c.a[h]*c.a[h]);
for(auto&v:dm)v*=1-c.p;
}}return ce;
}};

int main(int argc,char**argv){try{unsigned seed=argc>1?std::stoul(argv[1]):42;
Net net(seed);
std::mt19937 rng(seed+311);
auto sample=make(rng,1);
W grad{};
net.run(sample,&grad);
double error=0;
for(int i=0;
i<N;
i+=17){double old=net.w[i],e=1e-6;
net.w[i]=old+e;
double hi=net.run(sample);
net.w[i]=old-e;
double lo=net.run(sample);
net.w[i]=old;
error=std::max(error,std::abs((hi-lo)/(2*e)-grad[i]));
}if(error>1e-7)throw std::runtime_error("gradient mismatch");
std::vector<Seq>train;
for(int i=0;
i<256;
++i)train.push_back(make(rng,rng()%3));
for(int step=0;
step<1200;
++step){grad.fill(0);
for(auto&s:train)net.run(s,&grad);
for(int i=0;
i<N;
++i)net.w[i]-=.15*(grad[i]/256+.0001*net.w[i]);
}double tr=0;
int trcorrect=0;
for(auto&s:train){int a;
tr+=net.run(s,nullptr,&a);
trcorrect+=a==s.target;
}printf("seed=%u params=%d gradient=%.12g trainCE=%.9f trainacc=%.6f\n",seed,N,error,tr/256,trcorrect/256.);
for(int noise:{0,2,8,32}){std::mt19937 test(18181+noise);
int aok=0,bok=0;
double ce=0;
for(int i=0;
i<256;
++i){auto s=make(test,noise);
int a,b;
ce+=net.run(s,nullptr,&a,&b);
aok+=a==s.target;
bok+=b==s.target;
}printf("noise=%d n=256 soft=%.6f hard=%.6f CE=%.9f\n",noise,aok/256.,bok/256.,ce/256);
}return 0;
}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());
return 1;
}}
