// CPU-only compact DSB2 comparison; no model expansion, inference updates or writes.
#define NOMINMAX
#define TAO_INPUT_SCALE
#include "dual_model_bundle.hpp"
#include "tokenizer_file.hpp"
#include <iostream>
#include <iomanip>
using namespace tao::dual;
static std::string readbytes(const std::string&p){std::ifstream f(p,std::ios::binary|std::ios::ate);auto n=f.tellg();if(n<28||n>512ll*1024*1024)throw std::runtime_error("file size");f.seekg(0);std::string s(size_t(n),char(0));f.read(s.data(),s.size());if(!f)throw std::runtime_error("read");return s;}
static uint64_t u(const std::string&s,size_t p,int n){uint64_t v=0;for(int i=0;i<n;++i)v|=uint64_t((unsigned char)s.at(p+i))<<(8*i);return v;}
static float fp(const std::string&s,size_t p){uint32_t v=uint32_t(u(s,p,4));float x;std::memcpy(&x,&v,4);if(!std::isfinite(x))throw std::runtime_error("nonfinite");return x;}
struct Compact{std::string raw,hash;Config c;size_t start;
Compact(const std::string&p,const std::string&tok):raw(readbytes(p)),hash(tao::text::sha256(raw)){if(raw.substr(0,4)!="DSB2")throw std::runtime_error("DSB2");auto mn=u(raw,4,8),pn=u(raw,12,8);if(mn>1048576||pn<28||mn>raw.size()-28||pn!=raw.size()-28-mn||bundle_hash(raw.substr(28))!=u(raw,20,8))throw std::runtime_error("length/checksum");start=28+size_t(mn);if(raw.substr(start,4)!="DSM1")throw std::runtime_error("DSM1");c.layers=unsigned(u(raw,start+4,4));c.d=unsigned(u(raw,start+8,4));c.s=unsigned(u(raw,start+12,4));c.m=unsigned(u(raw,start+16,4));c.e=unsigned(u(raw,start+20,4));c.vocab=unsigned(u(raw,start+24,4));c.validate();if(c.layers>64||c.d>8192||c.s>8192||c.m>8192||c.e>32768||c.vocab>262144)throw std::runtime_error("bounds");if(model_bytes(c)!=pn||raw.substr(28,size_t(mn))!=bundle_manifest(c,tok))throw std::runtime_error("manifest");start+=28;}};
struct Stats{uint64_t n=0,rows=0,nza=0,nzb=0,support=0,flips=0,both=0,symbol=0,changed=0;double base=0,diff=0,srel=0,smax=0,sbase=0,sdiff=0;
void add(const Stats&v){n+=v.n;rows+=v.rows;nza+=v.nza;nzb+=v.nzb;support+=v.support;flips+=v.flips;both+=v.both;symbol+=v.symbol;changed+=v.changed;base+=v.base;diff+=v.diff;srel+=v.srel;smax=(std::max)(smax,v.smax);sbase+=v.sbase;sdiff+=v.sdiff;}
void emit(const std::string&kind,const std::string&name)const{auto r=[](double a,double b){return b?a/b:0.;};std::cout<<kind<<" name="<<name<<" n="<<n<<" rows="<<rows<<" qdensity_a="<<r(nza,n)<<" qdensity_b="<<r(nzb,n)<<" support_changes="<<support<<" support_fraction="<<r(support,n)<<" sign_flips="<<flips<<" common_nonzero="<<both<<" sign_flip_fraction_common="<<r(flips,both)<<" symbol_changes="<<symbol<<" effective_changes="<<changed<<" delta_rms="<<sqrt(r(diff,n))<<" effective_normalized_l2="<<(base?sqrt(diff/base):(diff?INFINITY:0))<<" scale_mean_abs_relative="<<r(srel,rows)<<" scale_max_abs_relative="<<smax<<" scale_normalized_l2="<<(sbase?sqrt(sdiff/sbase):0)<<"\n";}};
static void compare(const std::string&pa,const std::string&pb,const std::string&tok){Compact a(pa,tok),b(pb,tok);if(bundle_manifest(a.c,tok)!=bundle_manifest(b.c,tok))throw std::runtime_error("shapes");std::cout<<"PAIR a="<<pa<<" b="<<pb<<" sha256_a="<<a.hash<<" sha256_b="<<b.hash<<"\n";size_t ia=a.start,ib=b.start;Stats all,full;std::map<std::string,Stats>groups;
for(const auto&t:schema(a.c)){Stats z;z.n=t.elements();if(t.ternary){z.rows=t.rows;size_t stride=(size_t(t.cols)+3)/4;for(unsigned row=0;row<t.rows;++row){double sa=fp(a.raw,ia),sb=fp(b.raw,ib);ia+=4;ib+=4;if(sa<=0||sb<=0)throw std::runtime_error("scale");double sr=std::abs(sb-sa)/sa;z.srel+=sr;z.smax=(std::max)(z.smax,sr);z.sbase+=sa*sa;z.sdiff+=(sb-sa)*(sb-sa);for(size_t j=0;j<stride*4;++j){unsigned qa=(static_cast<unsigned char>(a.raw.at(ia+j/4))>>(2*(j%4)))&3,qb=(static_cast<unsigned char>(b.raw.at(ib+j/4))>>(2*(j%4)))&3;if(qa==3||qb==3||(j>=t.cols&&(qa||qb)))throw std::runtime_error("code/padding");if(j>=t.cols)continue;z.nza+=qa!=0;z.nzb+=qb!=0;z.support+=(qa!=0)!=(qb!=0);z.both+=qa&&qb;z.flips+=qa&&qb&&qa!=qb;z.symbol+=qa!=qb;double x=qa==0?0:qa==1?sa:-sa,y=qb==0?0:qb==1?sb:-sb;z.base+=x*x;z.diff+=(y-x)*(y-x);z.changed+=x!=y;}ia+=stride;ib+=stride;}all.add(z);groups[std::to_string(t.rows)+"x"+std::to_string(t.cols)].add(z);}else{for(size_t j=0;j<t.elements();++j){double x=fp(a.raw,ia),y=fp(b.raw,ib);ia+=4;ib+=4;z.base+=x*x;z.diff+=(y-x)*(y-x);z.changed+=x!=y;}full.add(z);}z.emit(t.ternary?"MATRIX":"FLOAT_TENSOR_QMETRICS_NA",t.name);}
if(ia!=a.raw.size()||ib!=b.raw.size())throw std::runtime_error("trailing");for(const auto&g:groups)g.second.emit("SHAPE",g.first);all.emit("AGGREGATE","ternary");full.emit("AGGREGATE","float_qmetrics_NA");if(tao::text::sha256(readbytes(pa))!=a.hash||tao::text::sha256(readbytes(pb))!=b.hash)throw std::runtime_error("input changed");std::cout<<"FROZEN_INPUTS_OK\n";}
int main(int argc,char**argv){try{if(argc!=5)throw std::runtime_error("usage: exe tokenizer.bbp step800.dsb step1200.dsb step1204.dsb");std::string tok;tao::text::load_tokenizer(argv[1],tok);std::cout<<std::setprecision(12)<<"TOKENIZER sha256="<<tok<<" normalized_l2_denominator=older_effective_l2 scale_relative_denominator=older_scale storage=pairwise_compact\n";compare(argv[2],argv[3],tok);compare(argv[3],argv[4],tok);compare(argv[2],argv[4],tok);return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
