#include <array>
#include <vector>
#include <random>
#include <cmath>
#include <cstdio>
#include <stdexcept>
#include <algorithm>
// Explicit structured-event probe. Query known before stream. Supervised gate labels.
struct Gate{std::array<double,81>w;Gate(unsigned seed){std::mt19937 r(seed);std::normal_distribution<double>d(0,.2);for(auto&v:w)v=d(r);}double run(int query,int object,std::array<double,81>*grad=nullptr)const{double h[8],x[8]={};x[query]=1;x[4+object]=1;for(int i=0;i<8;++i){double a=w[i*9+8];for(int d=0;d<8;++d)a+=w[i*9+d]*x[d];h[i]=std::tanh(a);}double z=w[80];for(int i=0;i<8;++i)z+=w[72+i]*h[i];double p=z>=0?1/(1+std::exp(-z)):std::exp(z)/(1+std::exp(z));if(grad){double dz=p-(query==object);(*grad)[80]+=dz;for(int i=0;i<8;++i){(*grad)[72+i]+=dz*h[i];double da=dz*w[72+i]*(1-h[i]*h[i]);(*grad)[i*9+8]+=da;for(int d=0;d<8;++d)(*grad)[i*9+d]+=da*x[d];}}return std::max(z,0.)-z*(query==object)+std::log1p(std::exp(-std::abs(z)));}double probability(int q,int o)const{double h[8],z=w[80];for(int i=0;i<8;++i)h[i]=std::tanh(w[i*9+8]+w[i*9+q]+w[i*9+4+o]);for(int i=0;i<8;++i)z+=w[72+i]*h[i];return z>=0?1/(1+std::exp(-z)):std::exp(z)/(1+std::exp(z));}};
int main(){try{for(unsigned seed:{42u,123u,2026u}){Gate g(seed);std::array<double,81>grad{};g.run(1,2,&grad);double maxerr=0;for(int i=0;i<81;++i){double old=g.w[i],e=1e-6;g.w[i]=old+e;double hi=g.run(1,2);g.w[i]=old-e;double lo=g.run(1,2);g.w[i]=old;maxerr=std::max(maxerr,std::abs((hi-lo)/(2*e)-grad[i]));}if(maxerr>1e-7)throw std::runtime_error("gradient");for(int step=0;step<10000;++step){grad.fill(0);for(int q=0;q<4;++q)for(int o=0;o<4;++o)g.run(q,o,&grad);for(int i=0;i<81;++i)g.w[i]-=.2*(grad[i]/16+.0001*g.w[i]);}int gateok=0;for(int q=0;q<4;++q)for(int o=0;o<4;++o)gateok+=(g.probability(q,o)>=.5)==(q==o);printf("seed=%u gate_pairs=%d/16 grad_error=%.12g\n",seed,gateok,maxerr);for(int noise:{0,1,3,16,64}){int correct[3]={},total=0;double softcorrect=0;for(int q=0;q<4;++q)for(int a=0;a<8;++a)for(int b=0;b<8;++b)if(a!=b)for(int update=0;update<2;++update){std::vector<std::pair<int,int>>events{{q,a}};for(int i=0;i<noise;++i)events.push_back({(q+1+i%3)%4,(a+i+1)%8});if(update)events.push_back({q,b});for(int i=0;i<noise;++i)events.push_back({(q+1+i%3)%4,(a+i+2)%8});int target=update?b:a;int memory=-1,always=-1,frozen=-1;double soft[8]={};for(auto ev:events){double p=g.probability(q,ev.first);if(p>=.5)memory=ev.second;always=ev.second;if(frozen<0)frozen=ev.second;for(int k=0;k<8;++k)soft[k]=(1-p)*soft[k]+p*(k==ev.second);}correct[0]+=memory==target;correct[1]+=always==target;correct[2]+=frozen==target;softcorrect+=int(std::max_element(soft,soft+8)-soft)==target;++total;}printf("noise_each_side=%d n=%d learned_hard=%.6f learned_soft=%.6f always_write=%.6f keep_first=%.6f\n",noise,total,double(correct[0])/total,softcorrect/total,double(correct[1])/total,double(correct[2])/total);}}return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
