#include "tao_ternary.hpp"
#include <array>
#include <random>
#include <cstdio>
#include <cmath>
#include <algorithm>
using State=std::array<int8_t,64>;
struct Chain{std::array<State,16>emb;Chain(unsigned seed){std::mt19937 r(seed);for(auto&e:emb)for(auto&v:e)v=int(r()%3)-1;}void push(State&s,int id,int mode)const{auto&e=emb[id];if(mode>=2){State old=s;for(int d=0;d<64;++d){int v=old[(d+63)%64]+e[d];s[d]=mode==2?tao::ternary::mod3(v):int8_t(v);}return;}if(mode==0){for(int d=0;d<64;++d)s[d]=tao::ternary::mod3(s[d]+e[d]);return;}for(int d=0;d<32;++d)s[d]=tao::ternary::mod3(s[d]+e[d]+s[32+d]*e[32+d]);for(int d=0;d<32;++d)s[32+d]=tao::ternary::mod3(s[32+d]+e[32+d]+s[(d+1)%32]*e[d]);}void pop(State&s,int id,int mode)const{auto&e=emb[id];if(mode>=2){State old=s;for(int d=0;d<64;++d){int v=old[(d+1)%64]-e[(d+1)%64];s[d]=mode==2?tao::ternary::mod3(v):int8_t(v);}return;}if(mode==0){for(int d=0;d<64;++d)s[d]=tao::ternary::mod3(s[d]-e[d]);return;}for(int d=0;d<32;++d)s[32+d]=tao::ternary::mod3(s[32+d]-e[32+d]-s[(d+1)%32]*e[d]);for(int d=0;d<32;++d)s[d]=tao::ternary::mod3(s[d]-e[d]-s[32+d]*e[32+d]);}};
struct Sample{State x;int y;bool test;int condition;};
int main(){try{for(unsigned seed:{42u,123u,2026u}){Chain c(seed);for(int mode=0;mode<4;++mode){std::vector<Sample>data;int collisions=0,totalpairs=0;for(int a=0;a<8;++a)for(int b=0;b<8;++b)if(a!=b)for(int o=0;o<4;++o)for(int layout=0;layout<2;++layout)for(int query=0;query<2;++query){State s{};std::vector<int>seq=layout==0?std::vector<int>{a,12,8+o,13,b}:std::vector<int>{b,13,8+o,12,a};if(layout)seq.insert(seq.end(),{15,8+(o+1)%4,15});seq.push_back(query?15:14);for(int id:seq)c.push(s,id,mode);State restored=s;for(auto it=seq.rbegin();it!=seq.rend();++it)c.pop(restored,*it,mode);if(restored!=State{})throw std::runtime_error("inverse failure");State reversed{};auto swapped=seq;for(auto&id:swapped){if(id==a)id=b;else if(id==b)id=a;}for(int id:swapped)c.push(reversed,id,mode);collisions+=s==reversed;++totalpairs;data.push_back({s,query?a:b,(std::min(a,b)+std::max(a,b)+o)%4==0,layout*2+query});}
// Train-only linear eight-class head; fixed features. Balanced swap partners in same split.
std::array<double,4*8*65>w{};int ntrain=0,ntest=0;for(auto&s:data)(s.test?ntest:ntrain)++;for(int step=0;step<1200;++step){std::array<double,4*8*65>g{};for(auto&s:data)if(!s.test){double z[8],mx=-1e300,sum=0;for(int v=0;v<8;++v){z[v]=w[s.condition*520+v*65+64];for(int d=0;d<64;++d)z[v]+=w[s.condition*520+v*65+d]*(double(s.x[d])*(mode==5?1/std::sqrt(6.):1.));mx=std::max(mx,z[v]);}for(int v=0;v<8;++v){z[v]=std::exp(z[v]-mx);sum+=z[v];}for(int v=0;v<8;++v){double delta=z[v]/sum-(v==s.y);for(int d=0;d<64;++d)g[s.condition*520+v*65+d]+=delta*(double(s.x[d])*(mode==5?1/std::sqrt(6.):1.));g[s.condition*520+v*65+64]+=delta;}}for(size_t i=0;i<w.size();++i)w[i]-=.15*(g[i]/ntrain+.001*w[i]);}
int correct[2]={};double ce[2]={};for(auto&s:data){double z[8],mx=-1e300,sum=0;int best=0;for(int v=0;v<8;++v){z[v]=w[s.condition*520+v*65+64];for(int d=0;d<64;++d)z[v]+=w[s.condition*520+v*65+d]*(double(s.x[d])*(mode==5?1/std::sqrt(6.):1.));if(z[v]>mx){mx=z[v];best=v;}}for(double v:z)sum+=std::exp(v-mx);ce[s.test]+=mx+std::log(sum)-z[s.y];correct[s.test]+=best==s.y;}printf("seed=%u mode=%s train=%d test=%d swap_collisions=%d/%d inverse=PASS train_acc=%.6f test_acc=%.6f train_CE=%.9f test_CE=%.9f\n",seed,mode==0?"sum":mode==1?"coupling":mode==2?"permutation_mod3":"permutation_wide",ntrain,ntest,collisions,totalpairs,double(correct[0])/ntrain,double(correct[1])/ntest,ce[0]/ntrain,ce[1]/ntest);}}return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
