// CPU-only decoded corpus audit. Output is UTF-8; markers are descriptive, not labels.
#define NOMINMAX
#include "tokenizer_file.hpp"
#include "bpe_pilot_reader.hpp"
#include <iostream>
#include <sstream>
#include <iomanip>
#include <algorithm>
#include <set>
static std::string readbytes(const std::string&p){std::ifstream f(p,std::ios::binary);if(!f)throw std::runtime_error("open "+p);std::string s((std::istreambuf_iterator<char>(f)),{});if(f.bad())throw std::runtime_error("read "+p);return s;}
static std::string snippet(const std::string&s,size_t cap=240){size_t end=(std::min)(cap,s.size());while(end<s.size()&&end&&((unsigned char)s[end]&192)==128)--end;std::string out;const char*hex="0123456789abcdef";for(size_t i=0;i<end;++i){unsigned char c=s[i];if(c=='\n')out+="\\n";else if(c=='\r')out+="\\r";else if(c=='\t')out+="\\t";else if(c=='"'||c=='\\'){out+='\\';out+=char(c);}else if(c<32||c==127){out+="\\x";out+=hex[c>>4];out+=hex[c&15];}else out+=char(c);}if(end<s.size())out+="...";return out;}
struct Marks{size_t bytes=0,ascii=0,letters=0,digits=0,han=0,math=0,invalid=0,latex=0;
void scan(const std::string&s){bytes+=s.size();latex+=s.find("\\frac")!=std::string::npos||s.find("\\begin")!=std::string::npos||s.find("\\(")!=std::string::npos||s.find("$$")!=std::string::npos;for(size_t i=0;i<s.size();){unsigned char c=s[i];if(c<128){++ascii;letters+=(c>='A'&&c<='Z')||(c>='a'&&c<='z');digits+=c>='0'&&c<='9';math+=std::string("=+*/^<>$").find(char(c))!=std::string::npos;++i;continue;}unsigned n=c>=0xc2&&c<=0xdf?2:c>=0xe0&&c<=0xef?3:c>=0xf0&&c<=0xf4?4:0;uint32_t cp=n?c&((1u<<(7-n))-1):0;bool ok=n&&i+n<=s.size();for(unsigned j=1;ok&&j<n;++j){unsigned char q=s[i+j];if((q&192)!=128)ok=false;else cp=(cp<<6)|(q&63);}if(ok&&(cp<(n==2?128u:n==3?2048u:65536u)||cp>0x10ffff||(cp>=0xd800&&cp<=0xdfff)))ok=false;if(!ok){++invalid;++i;continue;}han+=(cp>=0x3400&&cp<=0x4dbf)||(cp>=0x4e00&&cp<=0x9fff)||(cp>=0x20000&&cp<=0x323af);math+=cp>=0x2200&&cp<=0x22ff;i+=n;}}
void emit(const std::string&tag)const{std::cout<<tag<<" bytes="<<bytes<<" ascii_bytes="<<ascii<<" ascii_letters="<<letters<<" ascii_digits="<<digits<<" han_codepoints="<<han<<" math_markers="<<math<<" latex_marked_messages="<<latex<<" invalid_utf8_bytes="<<invalid;}};
struct Ref{std::string split;size_t doc,turn,len;};
using Repeats=std::map<std::string,std::vector<Ref>>;
static void audit(const std::string&path,const std::string&split,const tao::text::ByteBpe&b,const std::string&tok,Repeats&exact,Repeats&normalized){auto raw=readbytes(path);auto hash=tao::text::sha256(raw);std::istringstream in(raw);auto docs=tao::data::read_bpe_pilot(in,tok);if(docs.empty())throw std::runtime_error("empty corpus");std::cout<<"CORPUS split="<<split<<" path="<<path<<" sha256="<<hash<<" docs="<<docs.size()<<"\n";std::set<size_t>selected{0,docs.size()/2,docs.size()-1};Marks all,answers;std::vector<size_t>lengths;size_t targets=0,answerCount=0,totalTokens=0;
for(size_t d=0;d<docs.size();++d){const auto&t=docs[d];size_t docTargets=0;for(const auto&v:t)docTargets+=v.loss;targets+=docTargets;totalTokens+=t.size();std::cout<<"DOC split="<<split<<" index="<<d<<" tokens="<<t.size()<<" assistant_targets="<<docTargets<<" selected="<<selected.count(d)<<"\n";size_t p=1,turn=0;while(p<t.size()){bool assistant=t[p++].id==tao::data::ASSISTANT;std::vector<uint32_t>ids;while(p<t.size()&&t[p].id!=tao::data::TURN_END)ids.push_back(uint32_t(t[p++].id));if(p==t.size())throw std::runtime_error("turn boundary");++p;auto text=b.decode(ids);all.scan(text);if(assistant){++answerCount;lengths.push_back(ids.size()+1);answers.scan(text);Ref ref{split,d,turn,ids.size()+1};exact[tao::text::sha256(text)].push_back(ref);std::string norm;bool space=false;for(unsigned char c:text){if(c==' '||c=='\n'||c=='\r'||c=='\t'){space=!norm.empty();continue;}if(space){norm+=' ';space=false;}norm+=char(c>='A'&&c<='Z'?c+32:c);}normalized[tao::text::sha256(norm)].push_back(ref);}
if(selected.count(d)){Marks m;m.scan(text);std::cout<<"MESSAGE split="<<split<<" doc="<<d<<" turn="<<turn<<" role="<<(assistant?"assistant":"user")<<" body_tokens="<<ids.size()<<" targets_including_turn_end="<<(assistant?ids.size()+1:0)<<" ";m.emit("markers");std::cout<<" snippet=\""<<snippet(text)<<"\"\n";}++turn;}}
std::sort(lengths.begin(),lengths.end());auto q=[&](double f){return lengths.empty()?size_t(0):lengths[size_t(f*(lengths.size()-1))];};std::cout<<"SUMMARY split="<<split<<" tokens="<<totalTokens<<" targets="<<targets<<" assistant_answers="<<answerCount<<" answer_target_min="<<q(0)<<" p50="<<q(.5)<<" p90="<<q(.9)<<" max="<<q(1)<<" target_mean="<<(answerCount?double(targets)/answerCount:0)<<"\n";std::cout<<"MARKERS split="<<split<<" scope=all ";all.emit("counts");std::cout<<"\nMARKERS split="<<split<<" scope=assistant ";answers.emit("counts");std::cout<<"\n";if(tao::text::sha256(readbytes(path))!=hash)throw std::runtime_error("corpus changed");std::cout<<"FROZEN_CORPUS_OK split="<<split<<"\n";}
static void repeats(const Repeats&r,const char*kind){size_t groups=0,cross=0,occ=0;for(const auto&kv:r)if(kv.second.size()>1){++groups;occ+=kv.second.size();bool a=false,b=false;for(const auto&v:kv.second){a|=v.split=="train";b|=v.split=="validation";}cross+=a&&b;std::cout<<"REPEATED_ANSWER kind="<<kind<<" sha256="<<kv.first<<" count="<<kv.second.size()<<" cross_split="<<(a&&b)<<" refs=";size_t n=0;for(const auto&v:kv.second){if(n++==16){std::cout<<"...";break;}std::cout<<v.split<<":"<<v.doc<<":"<<v.turn<<":"<<v.len<<",";}std::cout<<"\n";}std::cout<<"REPEAT_SUMMARY kind="<<kind<<" groups="<<groups<<" occurrences_in_groups="<<occ<<" cross_split_groups="<<cross<<"\n";}
int main(int argc,char**argv){try{if(argc!=4)throw std::runtime_error("usage: exe tokenizer.bbp train.bin validation.bin");std::string tok;auto b=tao::text::load_tokenizer(argv[1],tok);std::cout<<std::setprecision(12)<<"TOKENIZER sha256="<<tok<<" indices=zero_based snippets=first_240_utf8_bytes markers=coarse_not_language_or_topic_classifier normalized_hash=ASCII_lowercase_whitespace_collapse_not_semantic_near_duplicate\n";Repeats e,n;audit(argv[2],"train",b,tok,e,n);audit(argv[3],"validation",b,tok,e,n);repeats(e,"exact_decoded_body");repeats(n,"ASCII_case_whitespace_normalized");std::string end;tao::text::load_tokenizer(argv[1],end);if(end!=tok)throw std::runtime_error("tokenizer changed");return 0;}catch(const std::exception&e){std::cerr<<"FAIL "<<e.what()<<"\n";return 1;}}
