#include "conversation_partition.hpp"
#include <arrow/api.h>
#include <arrow/io/file.h>
#include <parquet/arrow/reader.h>
#include <fstream>
#include <set>
#include <cstdio>
using namespace tao::data;
void u32(std::ostream&o,uint32_t v){for(int i=0;i<4;++i)o.put(char(v>>(8*i)));}
int main(){try{std::ofstream out("build/bpe_training_messages.bin",std::ios::binary),manifest("build/bpe_training_rows.tsv");out.write("BTM1",4);manifest<<"shard\trow\tconversation_hash\tprompt_hash\n";std::set<uint64_t>seen;size_t count=0,bytes=0,messages_count=0,rejected=0;for(int shard:{0,25,50}){char path[180];sprintf_s(path,"D:/Datasets/Infinity-Instruct/7M/train-%05d-of-00075.parquet",shard);auto input=arrow::io::ReadableFile::Open(path).ValueOrDie();auto reader=parquet::arrow::OpenFile(input,arrow::default_memory_pool()).ValueOrDie();std::shared_ptr<arrow::Table>table;auto status=reader->ReadTable(&table);if(!status.ok())throw std::runtime_error(status.ToString());table=table->CombineChunks().ValueOrDie();auto lists=std::static_pointer_cast<arrow::ListArray>(table->GetColumnByName("conversations")->chunk(0));auto structs=std::static_pointer_cast<arrow::StructArray>(lists->values());auto roles=std::static_pointer_cast<arrow::StringArray>(structs->GetFieldByName("from"));auto texts=std::static_pointer_cast<arrow::StringArray>(structs->GetFieldByName("value"));size_t before=count;
for(int64_t row=0;row<lists->length();++row){uint64_t mix=uint64_t(shard)*100000+row+0x9e3779b97f4a7c15ull;mix=(mix^(mix>>30))*0xbf58476d1ce4e5b9ull;mix=(mix^(mix>>27))*0x94d049bb133111ebull;mix^=mix>>31;if(mix%100>=10)continue;std::vector<Message>m,p;bool valid=!lists->IsNull(row);size_t n=0;for(int64_t j=lists->value_offset(row);valid&&j<lists->value_offset(row)+lists->value_length(row);++j){if(roles->IsNull(j)||texts->IsNull(j)){valid=false;break;}auto role=roles->GetString(j);if(role!="human"&&role!="gpt"){valid=false;break;}m.push_back({role=="gpt",texts->GetString(j)});n+=m.back().utf8.size();if(role=="human")p.push_back(m.back());}if(!valid||m.empty()||n>65536){++rejected;continue;}auto ph=fingerprint(p.empty()?m:p);if(partition(ph)!=Partition::train)continue;auto h=fingerprint(m);if(!seen.insert(h).second)continue;manifest<<shard<<'\t'<<row<<'\t'<<h<<'\t'<<ph<<'\n';for(auto&msg:m){u32(out,uint32_t(msg.utf8.size()));out.write(msg.utf8.data(),msg.utf8.size());++messages_count;}bytes+=n;++count;}printf("shard=%d selected_train_docs=%zu\n",shard,count-before);}
out.close();manifest.close();if(!out||!manifest)throw std::runtime_error("write");printf("PASS docs=%zu messages=%zu utf8_bytes=%zu rejected=%zu\n",count,messages_count,bytes,rejected);return 0;}catch(const std::exception&e){printf("FAIL %s\n",e.what());return 1;}}
