#define TAO_ASYNC_D2D
#define TAO_DEFER_BACKWARD_SYNC
#define TAO_DEVICE_ZERO_GRAD
#define TAO_INPUT_SCALE
#include "dual_state_sorted_trainer.cuh"
#include <random>
#include <fstream>
#include <cstdio>
using namespace tao::dual;
Node forward(TrainGraph& z,unsigned token,bool ff){auto& c=z.c;auto& tape=z.tape;auto& w=z.w;auto& s=z.s;auto& m=z.m;auto x=tape.scaled(tape.embedding(w.at("embedding"),token,c.d),std::sqrt(float(c.d)));
for(unsigned l=0;l<c.layers;++l){auto p="layer."+std::to_string(l)+".";auto xn=tape.norm(x,w.at(p+"input.norm"));auto branch=[&](std::string name,bool mem){unsigned n=mem?c.m:c.s;auto z=tape.add(tape.linear(w.at(p+name+".x"),xn,n),tape.linear(w.at(p+name+".s"),s[l],n));if(mem)z=tape.add(z,tape.linear(w.at(p+name+".m"),m[l],n));return tape.add(z,w.at(p+name+".bias"));};auto u=branch("s.candidate",false),a=branch("s.gate",false);s[l]=tape.update(s[l],u,a);auto v=branch("m.candidate",true),g=branch("m.gate",true);m[l]=tape.update(m[l],v,g);auto r=tape.add(tape.linear(w.at(p+"read.s"),s[l],c.d),tape.linear(w.at(p+"read.m"),m[l],c.d));x=tape.add(x,tape.norm(r,w.at(p+"read.norm")));}return tape.add(tape.linear(w.at("embedding"),tape.norm(x,w.at("final.norm")),c.vocab),w.at("vocab.bias"));}
void reset(SortedGpuTrainer& t){t.graph.tape.reverse.clear();for(auto& x:t.graph.s)x=t.graph.tape.leaf(Vec(t.graph.c.s));for(auto& x:t.graph.m)x=t.graph.tape.leaf(Vec(t.graph.c.m));}
Node example(SortedGpuTrainer& t,bool ff,int a,int b,int query,int noise){reset(t);Node y;std::vector<int> ids={10,20+a,11,20+b};if(noise==1)ids.push_back(40);if(noise==2)for(int k=0;k<4;k++)ids.push_back(40+k%2);if(noise==3){ids.push_back(10);ids.push_back(20+a);}if(noise==4){ids={11,20+b,10,20+a};}if(noise==6){ids={11,20+b,12,20+(a+b)%8,40,10,20+a,10,20+a};}if(noise==5){ids.push_back(12);ids.push_back(20+(a+b)%8);}ids.push_back(30);ids.push_back(10+query);for(int id:ids)y=forward(t.graph,id,ff);return y;}
void evaluate(SortedGpuTrainer& t,bool ff,int step){for(int split=0;split<8;split++){double loss=0;int correct=0,n=0;for(int a=0;a<8;a++)for(int b=0;b<8;b++){int partition=(b-a+8)%8;bool held=partition>=6; if(split==0&&held)continue;if(split>0&&(!held||partition==7))continue;for(int q=0;q<2;q++){auto y=example(t,ff,a,b,q,split>1?split-1:0);auto v=y->value.host();int target=20+(q?b:a);float mx=*std::max_element(v.begin(),v.end());double sum=0;for(float x:v)sum+=std::exp(x-mx);loss+=std::log(sum)+mx-v[target];correct+=int(std::max_element(v.begin(),v.end())-v.begin())==target;n++;}}printf("METRIC ff=%d step=%d split=%d correct=%d n=%d nll=%.6f\n",ff,step,split,correct,n,loss/n);fflush(stdout);}reset(t);}
int main(int argc,char**argv){try{if(argc!=5)throw std::runtime_error("usage: noffn_learning 0 SEED AUGMENT UPDATES");int mode=atoi(argv[1]);if(mode!=0)throw std::runtime_error("no FFN only");bool ff=false;int seed=atoi(argv[2]);int augment=atoi(argv[3]);int updates=atoi(argv[4]);if(updates<100||updates>3000)throw std::runtime_error("updates");Config c;c.layers=2;c.d=64;c.s=16;c.m=64;c.e=mode==2?64:128;c.vocab=261;CpuModel cpu(c);for(auto& kv:cpu.w){unsigned h=seed;for(unsigned char ch:kv.first)h=h*16777619u^ch;std::mt19937 init(h);std::normal_distribution<float> nd(0,.15f);for(float& x:kv.second)x=kv.first.find("norm")!=std::string::npos?1.f:nd(init);}SortedGpuTrainer t(cpu);if(!ff){t.spec.erase(std::remove_if(t.spec.begin(),t.spec.end(),[](const TensorSpec& s){return s.name.find(".ff.")!=std::string::npos;}),t.spec.end());}for(auto it=t.graph.w.begin();it!=t.graph.w.end();){if(it->first.find(".ff.")!=std::string::npos){auto key=it->first;t.master.erase(key);t.moment.erase(key);t.variance.erase(key);t.scales.erase(key);cpu.w.erase(key);it=t.graph.w.erase(it);}else ++it;}size_t np=0;for(auto& sp:t.spec)np+=sp.elements();printf("CONFIG seed=%d ff=%d active_parameters=%zu layers=2 d=64 s=16 m=64 e=128 updates=CLI batch=4 test_partition7=sealed\n",seed,ff,np);printf("DETAIL mode=%d augment=%d e=%u\n",mode,augment,c.e);std::mt19937 rng(900),noise_rng(1200);for(int step=1;step<=updates;step++){t.zero_grad();for(int j=0;j<4;j++){int a=rng()%8,b=rng()%8;while((b-a+8)%8>=6)b=rng()%8;int q=rng()%2;auto y=example(t,ff,a,b,q,augment==2?int(noise_rng()%6):(augment==3?(step<=100?0:int(noise_rng()%6)):0));seed_loss(y,20+(q?b:a),true);t.graph.tape.backward();}reset(t);t.update(4,.003f);if(step%100==0){std::string path=std::string("D:/TaoVm/build/fresh_noffn_")+argv[4]+"_aug_"+argv[3]+"_seed_"+argv[2]+"_step_"+std::to_string(step)+".bin";std::ofstream out(path,std::ios::binary);for(auto* map:{&t.master,&t.moment,&t.variance})for(auto& kv:*map){auto v=kv.second->host();out.write((char*)v.data(),v.size()*4);}if(step==updates)evaluate(t,ff,step);}}return 0;}catch(const std::exception& e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}