#pragma once
#include "slot_resume_snapshot.cuh"
#include "dual_model_bundle.hpp"
namespace tao::dual {
inline std::string checkpoint_identity(const Config&c,const std::string&data,const std::string&tokenizer,uint64_t budget){if(data.size()!=64||data.find_first_not_of("0123456789abcdef")!=std::string::npos||!budget)throw std::runtime_error("checkpoint identity");return bundle_manifest(c,tokenizer)+data+"\n"+std::to_string(budget)+"\nprojection-sorted-v1-adamw-v1\n";}
inline void save_slot_file(const SlotSnapshot&a,const std::string&path,const std::string&id){if(std::filesystem::exists(path)||std::filesystem::exists(path+".tmp"))throw std::runtime_error("exists");std::ostringstream out(std::ios::binary|std::ios::out);auto u=[&](uint64_t v){for(int i=0;i<8;++i)out.put(char(v>>(8*i)));};u(id.size());out<<id;u(a.steps);u(a.next);for(auto&x:a.cursor){u(x.doc);u(x.target);}auto vec=[&](const Vec&v){for(float x:v){if(!std::isfinite(x))throw std::runtime_error("finite");uint32_t b;std::memcpy(&b,&x,4);for(int i=0;i<4;++i)out.put(char(b>>(8*i)));}};for(auto*map:{&a.w,&a.m,&a.v})for(auto&kv:*map)vec(kv.second);for(auto*state:{&a.s,&a.mem})for(auto&slot:*state)for(auto&v:slot)vec(v);auto body=out.str();std::ofstream f(path+".tmp",std::ios::binary);f.write("SCP1",4);uint64_t h=bundle_hash(body);for(int i=0;i<8;++i)f.put(char(h>>(8*i)));f.write(body.data(),body.size());f.close();if(!f)throw std::runtime_error("write");std::filesystem::rename(path+".tmp",path);}
// Expected template supplies exact model/slot tensor shapes; reject before GPU mutation.
inline SlotSnapshot load_slot_file(const std::string&path,const std::string&id,const SlotSnapshot&expected,const tao::data::PilotCursor&data){std::ifstream f(path,std::ios::binary|std::ios::ate);auto length=f.tellg();uint64_t floats=0;for(auto*map:{&expected.w,&expected.m,&expected.v})for(auto&kv:*map)floats+=kv.second.size();for(auto*states:{&expected.s,&expected.mem})for(auto&slot:*states)for(auto&v:slot)floats+=v.size();uint64_t bytes=12+8+id.size()+16+16*expected.cursor.size()+4*floats;if(length<0||uint64_t(length)!=bytes)throw std::runtime_error("length");f.seekg(0);std::string b(size_t(bytes),char(0));f.read(b.data(),b.size());if(!f||b.substr(0,4)!="SCP1")throw std::runtime_error("header");size_t p=4;auto u=[&](){if(p+8>b.size())throw std::runtime_error("truncated");uint64_t v=0;for(int i=0;i<8;++i)v|=uint64_t((unsigned char)b[p++])<<(8*i);return v;};auto hash=u();if(hash!=bundle_hash(b.substr(12)))throw std::runtime_error("checksum");if(u()!=id.size()||b.substr(p,id.size())!=id)throw std::runtime_error("identity");p+=id.size();auto a=expected;auto step=u();if(step>UINT32_MAX)throw std::runtime_error("step overflow");a.steps=unsigned(step);a.next=u();if(a.next>data.docs.size())throw std::runtime_error("next");for(auto&c:a.cursor){c.doc=u();c.target=u();if(c.doc==std::numeric_limits<size_t>::max()){if(c.target!=1)throw std::runtime_error("empty cursor");}else if(c.doc>=a.next||c.doc>=data.docs.size()||c.target<1||c.target>data.docs[c.doc].size())throw std::runtime_error("cursor");}auto vec=[&](Vec&v){for(float&x:v){uint32_t bits=0;for(int i=0;i<4;++i)bits|=uint32_t((unsigned char)b.at(p++))<<(8*i);std::memcpy(&x,&bits,4);if(!std::isfinite(x))throw std::runtime_error("finite");}};for(auto*map:{&a.w,&a.m,&a.v})for(auto&kv:*map)vec(kv.second);for(auto*states:{&a.s,&a.mem})for(auto&slot:*states)for(auto&v:slot)vec(v);for(auto&kv:a.v)for(float x:kv.second)if(x<0)throw std::runtime_error("variance");if(p!=b.size())throw std::runtime_error("trailing");return a;}
}
