#pragma once
#include "dual_sequence_slots.cuh"
#include "pilot_slot_cursor.hpp"
namespace tao::dual {
// In-memory step-boundary snapshot; portable disk encoding remains separate.
struct SlotSnapshot{std::map<std::string,Vec>w,m,v;std::vector<std::vector<Vec>>s,mem;std::vector<tao::data::Cursor>cursor;size_t next;unsigned steps;};
inline SlotSnapshot capture(SequenceSlots&slots,tao::data::PilotCursor&data){auto&t=slots.trainer;if(slots.active!=-1||!t.graph.tape.reverse.empty())throw std::runtime_error("not boundary");for(auto&kv:t.graph.w)for(float x:kv.second->grad.host())if(x!=0)throw std::runtime_error("pending gradient");SlotSnapshot a;for(auto&spec:t.spec){a.w[spec.name]=t.master.at(spec.name)->host();a.m[spec.name]=t.moment.at(spec.name)->host();a.v[spec.name]=t.variance.at(spec.name)->host();}for(size_t i=0;i<slots.s.size();++i){std::vector<Vec>s,m;for(unsigned l=0;l<t.graph.c.layers;++l){s.push_back(slots.s[i][l]->value.host());m.push_back(slots.m[i][l]->value.host());}a.s.push_back(s);a.mem.push_back(m);}a.cursor=data.slots;a.next=data.next;a.steps=t.steps;return a;}
inline void restore(const SlotSnapshot&a,SequenceSlots&slots,tao::data::PilotCursor&data){auto&t=slots.trainer;if(slots.active!=-1||!t.graph.tape.reverse.empty()||a.s.size()!=slots.s.size()||a.cursor.size()!=data.slots.size())throw std::runtime_error("restore shape");auto put=[](Device&d,const Vec&v){if(d.n!=v.size())throw std::runtime_error("size");for(float x:v)if(!std::isfinite(x))throw std::runtime_error("finite");check(cudaMemcpy(d.p,v.data(),v.size()*4,cudaMemcpyHostToDevice));};for(auto&spec:t.spec){put(*t.master.at(spec.name),a.w.at(spec.name));put(*t.moment.at(spec.name),a.m.at(spec.name));put(*t.variance.at(spec.name),a.v.at(spec.name));}for(size_t i=0;i<slots.s.size();++i)for(unsigned l=0;l<t.graph.c.layers;++l){put(slots.s[i][l]->value,a.s.at(i).at(l));put(slots.m[i][l]->value,a.mem.at(i).at(l));}data.slots=a.cursor;data.next=a.next;t.steps=a.steps;t.project();t.zero_grad();}
}
