#define main legacy_main
#include "diagnose_token_write.cpp"
#undef main
#include "token_write_hard.hpp"
#include <fstream>
#include <chrono>
int main(int argc,char**argv){try{unsigned seed=argc>1?std::stoul(argv[1]):42;Net net(seed);std::ifstream f("build/token_write_adam_"+std::to_string(seed)+".weights",std::ios::binary);if(!f.read((char*)net.w.data(),sizeof(net.w))||f.peek()!=EOF)throw std::runtime_error("weight shape");tao::TokenWriteHard model(net.w);std::mt19937 rng(321991);int cases=0,correct=0,agree=0;size_t writes=0,tokens=0;for(int noise:{0,1,3,16,128,512})for(int i=0;i<64;++i){auto s=make(rng,noise);int ref;net.run(s,nullptr,nullptr,&ref);model.reset();for(int t:s.tokens)model.step(s.query,t);if(model.memory!=ref)throw std::runtime_error("hard parity");agree++;correct+=model.memory==s.target;cases++;writes+=model.writes;tokens+=s.tokens.size();}printf("seed=%u hard_parity=%d/%d accuracy=%.6f write_rate=%.6f\n",seed,agree,cases,double(correct)/cases,double(writes)/tokens);
// Perturb only distractor owners; hard output must remain same, while changing final relevant owner must change answer.
int invariant=0,sensitive=0;for(int i=0;i<256;++i){auto s=make(rng,8);auto altered=s;for(size_t t=0;t<s.tokens.size();t+=3)if(s.tokens[t]!=s.query)altered.tokens[t+1]=4+(altered.tokens[t+1]-4+1)%8;model.reset();for(int t:altered.tokens)model.step(altered.query,t);invariant+=model.memory==s.target;auto changed=s;for(size_t t=changed.tokens.size();t>0;t-=3)if(changed.tokens[t-3]==s.query){changed.tokens[t-2]=4+(s.target+1)%8;break;}model.reset();for(int t:changed.tokens)model.step(changed.query,t);sensitive+=model.memory==(s.target+1)%8;}printf("counterfactual unchanged=%d/256 changed=%d/256\n",invariant,sensitive);
auto sample=make(rng,32);volatile int sink=0;double times[9];for(int r=0;r<9;++r){auto start=std::chrono::steady_clock::now();for(int i=0;i<500;++i){model.reset();for(int t:sample.tokens)sink+=model.step(sample.query,t);}times[r]=std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-start).count()/(500*sample.tokens.size());}std::sort(times,times+9);printf("hard_us_per_token min=%.6f median=%.6f max=%.6f tokens_per_seq=%zu sink=%d\n",times[0],times[4],times[8],sample.tokens.size(),int(sink));return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
