#include "tao_joint_selector.hpp"
#include <cstdio>
#include <random>
using namespace tao::joint;
void need(bool b){if(!b)throw std::runtime_error("check failed");}
template<class F>void rejects(F f){bool b=false;try{f();}catch(const std::exception&){b=true;}need(b);}
double loss(const Input&x,const Vector&u){auto y=forward(x);double sum=0;for(size_t d=0;d<u.size();++d)sum+=u[d]*y.soft[d];return sum;}
int main(){try{double maxerr=0;int comparisons=0;std::mt19937 rng(51);std::uniform_real_distribution<double>dist(-1,1);for(int trial=0;trial<40;++trial){Input x{{dist(rng),dist(rng),dist(rng)},{{dist(rng),dist(rng),dist(rng)},{dist(rng),dist(rng),dist(rng)}},{dist(rng),dist(rng),dist(rng),dist(rng),dist(rng)},.7,.3,.4};Vector u{dist(rng),dist(rng),dist(rng)};auto g=backward(x,u);auto verify=[&](double&parameter,double analytic){double old=parameter,h=1e-6;parameter=old+h;double hi=loss(x,u);parameter=old-h;double lo=loss(x,u);parameter=old;double err=std::abs((hi-lo)/(2*h)-analytic);maxerr=std::max(maxerr,err);need(err<1e-7);++comparisons;};for(size_t i=0;i<x.logits.size();++i)verify(x.logits[i],g.logits[i]);for(size_t d=0;d<3;++d){verify(x.original[d],g.original[d]);for(size_t j=0;j<2;++j)verify(x.values[j][d],g.values[j][d]);}verify(x.alpha,g.alpha);verify(x.beta,g.beta);}
Input empty{{1,-2},{},{9}};auto e=forward(empty);need(e.probability==Vector{1}&&e.hard==empty.original&&e.soft==empty.original);need(backward(empty,{1,1}).logits==Vector{0});Input x{{2},{{6}},{0,0,0}};need(forward(x).choice==0);x.logits={0,20,0};x.temperature=.01;need(forward(x).choice==1&&forward(x).soft==forward(x).hard);x.logits={0,0,20};need(forward(x).hard==Vector{3.5});
rejects([&]{auto z=x;z.temperature=0;forward(z);});rejects([&]{auto z=x;z.logits[0]=NAN;forward(z);});rejects([&]{auto z=x;z.values[0].clear();forward(z);});rejects([&]{backward(x,{NAN});});need(clipped_ste(.1,1,3)==3&&clipped_ste(2,1,3)==0);
std::array<uint8_t,32>hash{};tao::TernaryEmbedding head(3,2,hash);head.set_row(0,{1,0},1);head.set_row(1,{0,1},1);head.set_row(2,{1,1},1);need(scores(head,{2},{{3},{4}},{.5,-.5})==Vector({2,3.5,5.5,3.5,5.5}));
// Train only temporary joint logits, NOT model weights or a language task.
Input train{{0},{{4},{-4}},{0,0,0,0,0}};train.alpha=.5;train.beta=1;double first=0;for(int step=0;step<400;++step){auto y=forward(train);double err=y.soft[0]-4;if(step==0)first=.5*err*err;auto g=backward(train,{err});for(size_t k=0;k<train.logits.size();++k)train.logits[k]-=.5*g.logits[k];}auto y=forward(train);double final=.5*(y.soft[0]-4)*(y.soft[0]-4);need(final<first*.01&&y.choice==2);printf("PASS finite differences comparisons=%d max_abs=%.12g;empty/ties/temperature/nonfinite/head/STE\n",comparisons,maxerr);printf("TOY logit optimization loss %.9f -> %.9f hard_choice=%zu soft=%.9f hard=%.9f (not language training)\n",first,final,y.choice,y.soft[0],y.hard[0]);return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
