#define main server_main
#include "tao_d256_api.cpp"
#undef main
#include "tao_joint_selector.hpp"
#include <cstdio>
using Vec=std::vector<double>;
struct HeadResult{double ce;Vec logits,gradient;};
HeadResult head(const FixedBoundariesModel&m,const Vec&s,const Vec&bias,int target){if(s.size()!=320||bias.size()!=1024||target<0||target>=1024)throw std::invalid_argument("head shape");tao::joint::finite(s);tao::joint::finite(bias);Vec g(320),u(320),sig(320),h(320);for(int i=0;i<320;++i){g[i]=m.b_sgl_gate[i];u[i]=m.b_sgl_up[i];for(int d=0;d<320;++d){g[i]+=m.W_sgl_gate[i*320+d]*s[d];u[i]+=m.W_sgl_up[i*320+d]*s[d];}sig[i]=g[i]>=0?1/(1+std::exp(-g[i])):std::exp(g[i])/(1+std::exp(g[i]));h[i]=g[i]*sig[i]*u[i];}HeadResult out;out.logits=bias;for(int v=0;v<1024;++v)for(int i=0;i<320;++i)out.logits[v]+=m.W_sgl_out[v*320+i]*h[i];tao::joint::finite(out.logits);double mx=*std::max_element(out.logits.begin(),out.logits.end()),sum=0;for(double z:out.logits)sum+=std::exp(z-mx);out.ce=mx+std::log(sum)-out.logits[target];Vec dh(320);for(int v=0;v<1024;++v){double dz=std::exp(out.logits[v]-mx)/sum-(v==target);for(int i=0;i<320;++i)dh[i]+=m.W_sgl_out[v*320+i]*dz;}out.gradient.assign(320,0);for(int i=0;i<320;++i){double dg=dh[i]*u[i]*(sig[i]+g[i]*sig[i]*(1-sig[i])),du=dh[i]*g[i]*sig[i];for(int d=0;d<320;++d)out.gradient[d]+=dg*m.W_sgl_gate[i*320+d]+du*m.W_sgl_up[i*320+d];}tao::joint::finite(out.gradient);return out;}
void need(bool x){if(!x)throw std::runtime_error("check failed");}
int main(){try{ServerCore core;need(core.load("tao_fixed_step50002.bin","tao_context_supported.tcg","tao_coef_rts1_128.reader","tinystories_train.txt","experiments/d256_nibble64_baseline/train_tokens.bin"));std::ifstream file("experiments/d256_nibble64_baseline/train_tokens.bin",std::ios::binary);file.seekg(4);std::vector<int>tokens(68);need(bool(file.read((char*)tokens.data(),tokens.size()*4)));double maxparity=0,maxhead=0,maxselect=0,maxweight=0;for(int example=0;example<4;++example){std::vector<int>win(tokens.begin()+example,tokens.begin()+example+64);int target=tokens[example+64];SelfDecodingNode<16,256>node;for(int id:win)node.push(id,[&](int id){return core.q1.code(id);});Vec state(320),bias(1024);auto cursor=node;for(int k=0;;++k){for(int d=0;d<256;++d)state[d]+=core.reader_sel[k*256+d]*cursor.trit[d];if(!cursor.count)break;cursor.pop([&](int id){return core.q1.code(id);});}for(int i=0;i<64;++i)state[256+i]=double(float((node.hash>>(4*(i&7)))&15)/15.f-.5f);for(int v=0;v<1024;++v){float hist=0;for(int k=1;k<=15;++k)hist+=float(core.gates[win.back()*15+k-1])/32*core.model.Wbi[win[63-k]*1024+v];bias[v]=double(core.model.Wbi[win[62]*1024+v]+hist);}auto base=head(core.model,state,bias,target);std::vector<float>served;core.forward_window(win,served);for(int v=0;v<1024;++v)maxparity=std::max(maxparity,std::abs(base.logits[v]-served[v]));
for(int d=0;d<320;d+=17){double old=state[d],eps=1e-5;state[d]=old+eps;double hi=head(core.model,state,bias,target).ce;state[d]=old-eps;double lo=head(core.model,state,bias,target).ce;state[d]=old;maxhead=std::max(maxhead,std::abs((hi-lo)/(2*eps)-base.gradient[d]));}
// Selector acts only on reader256;hash64 and frozen Wbi remain unchanged.
tao::joint::Input x;x.original.assign(state.begin(),state.begin()+256);cursor=node;for(int k=1;k<=2;++k){cursor.pop([&](int id){return core.q1.code(id);});Vec candidate(256);for(int d=0;d<256;++d)candidate[d]=cursor.trit[d];x.values.push_back(candidate);}x.alpha=.05;x.beta=.05;
// Actual ternary score weights represented as q*scale; independently perturbed effective weights for derivative checks.
Vec weights(3*512);for(size_t i=0;i<weights.size();++i)weights[i]=(int(i%3)-1)*.001;auto score=[&](){Vec z(5);for(int d=0;d<256;++d)z[0]+=weights[d]*x.original[d];for(int j=0;j<2;++j)for(int a=1;a<=2;++a)for(int d=0;d<256;++d)z[1+2*j+a-1]+=weights[a*512+d]*x.original[d]+weights[a*512+256+d]*x.values[j][d];return z;};x.logits=score();auto objective=[&](){auto y=tao::joint::forward(x);Vec s=state;std::copy(y.soft.begin(),y.soft.end(),s.begin());return head(core.model,s,bias,target);};auto result=objective();Vec upstream(result.gradient.begin(),result.gradient.begin()+256);auto grad=tao::joint::backward(x,upstream);for(int k=0;k<5;++k){double old=x.logits[k],eps=1e-5;x.logits[k]=old+eps;double hi=objective().ce;x.logits[k]=old-eps;double lo=objective().ce;x.logits[k]=old;maxselect=std::max(maxselect,std::abs((hi-lo)/(2*eps)-grad.logits[k]));}
for(int index:{0,17,512,777,1024,1400}){int a=index/512,d=index%512;double analytic=0;if(a==0){if(d<256)analytic=grad.logits[0]*x.original[d];}else for(int j=0;j<2;++j)analytic+=grad.logits[1+2*j+a-1]*(d<256?x.original[d]:x.values[j][d-256]);double old=weights[index],eps=1e-5;weights[index]=old+eps;x.logits=score();double hi=objective().ce;weights[index]=old-eps;x.logits=score();double lo=objective().ce;weights[index]=old;x.logits=score();maxweight=std::max(maxweight,std::abs((hi-lo)/(2*eps)-analytic));}
double before=objective().ce; // Backtracking logit update is diagnostic,not model training.
double after=before;for(double lr:{.01,.001,.0001}){auto saved=x.logits;for(int k=0;k<5;++k)x.logits[k]-=lr*grad.logits[k];after=objective().ce;if(after<=before)break;x.logits=saved;after=before;}need(after<=before);auto hard=tao::joint::hard_forward(x);Vec hs=state;std::copy(hard.value.begin(),hard.value.end(),hs.begin());printf("EXAMPLE %d target=%d baseline_CE=%.9f soft_CE=%.9f after_logit_step=%.9f hard_CE=%.9f choice=%zu\n",example,target,base.ce,before,after,head(core.model,hs,bias,target).ce,hard.choice);}
need(maxparity<.0002&&maxhead<1e-6&&maxselect<1e-6&&maxweight<1e-5);printf("PASS frozen head serving max_abs=%.12g input_gradient=%.12g selector_gradient=%.12g effective_weight_gradient=%.12g\n",maxparity,maxhead,maxselect,maxweight);return 0;}catch(const std::exception&e){fprintf(stderr,"FAIL %s\n",e.what());return 1;}}
